//Categories

export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORIES_FULFILLED = "GET_CATEGORIES_FULFILLED";

export const GET_CATEGORIES_EVENT = "GET_CATEGORIES_EVENT";
export const GET_CATEGORIES_EVENT_FULFILLED = "GET_CATEGORIES_EVENT_FULFILLED";

//Event
export const GET_EVENT = "GET_EVENT";
export const GET_EVENT_PENDING = "GET_EVENT_PENDING";
export const GET_EVENT_REJECTED = "GET_EVENT_REJECTED";
export const GET_EVENT_FULFILLED = "GET_EVENT_FULFILLED";

export const GET_DETAIL_EVENT = "GET_DETAIL_EVENT";
export const GET_DETAIL_EVENT_FULFILLED = "GET_DETAIL_EVENT_FULFILLED";

export const POST_EVENT = "POST_EVENT";
export const POST_EVENT_PENDING = "POST_EVENT_PENDING";
export const POST_EVENT_REJECTED = "POST_EVENT_REJECTED";
export const POST_EVENT_FULFILLED = "POST_EVENT_FULFILLED";

//Order
export const GET_ORDERPEND = "GET_ORDERPEND";
export const GET_ORDERPEND_FULFILLED = "GET_ORDERPEND_FULFILLED";

export const GET_ORDERCONFIRM = "GET_ORDERCONFIRM";
export const GET_ORDERCONFIRM_FULFILLED = "GET_ORDERCONFIRM_FULFILLED";

export const GET_ORDERAPPROVED = "GET_ORDERAPPROVED";
export const GET_ORDERAPPROVED_FULFILLED = "GET_ORDERAPPROVED_FULFILLED";

export const POST_ORDER = "POST_ORDER";
export const POST_ORDER_PENDING = "POST_ORDER_PENDING";
export const POST_ORDER_REJECTED = "POST_ORDER_REJECTED";
export const POST_ORDER_FULFILLED = "POST_ORDER_FULFILLED";

export const PUT_ORDER = "PUT_ORDER";
export const PUT_ORDER_PENDING = "PUT_ORDER_PENDING";
export const PUT_ORDER_REJECTED = "PUT_ORDER_REJECTED";
export const PUT_ORDER_FULFILLED = "PUT_ORDER_FULFILLED";
